version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
      ADMIN_EMAIL: 'admin@admin.com'
      ADMIN_PASSWORD: '123456abc'
    ports:
      - '8888:8888'
    volumes:
      - .:/replica-youtube-api
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
